# Build against Numpy 2.0.0rc1.
# Delete this file once Numpy 2.0.0 is out.
channel_sources:
  - conda-forge/label/numpy_dev,conda-forge
numpy:
  - '2.0.0rc1'
  - '2.0.0rc1'
  - '2.0.0rc1'
python:
  - '3.9'
  - '3.10'
  - '3.11'
python_impl:
  - cpython
  - cpython
  - cpython
