{% set name = "ligo.skymap" %}
{% set version = "0.3.0" %}
{% set sha256 = "0f70769c7a410d8f7e2197d4a0c2c7f0dff4aa0072729d70b94b302350d92edf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # remove lalsuite requirement, since we can list dependencies explicitly here
    - setup.cfg-no-lalsuite.patch
    # workaround for missing alloc_aligned
    - 0001-Add-workaround-for-aligned_alloc-missing-on-old-vers.patch

build:
  entry_points:
    - bayestar-inject = ligo.skymap.tool.bayestar_inject:main
    - bayestar-localize-coincs = ligo.skymap.tool.bayestar_localize_coincs:main
    - bayestar-localize-lvalert = ligo.skymap.tool.bayestar_localize_lvalert:main
    - bayestar-mcmc = ligo.skymap.tool.bayestar_mcmc:main
    - bayestar-realize-coincs = ligo.skymap.tool.bayestar_realize_coincs:main
    - bayestar-sample-model-psd = ligo.skymap.tool.bayestar_sample_model_psd:main
    - ligo-skymap-combine = ligo.skymap.tool.ligo_skymap_combine:main
    - ligo-skymap-contour = ligo.skymap.tool.ligo_skymap_contour:main
    - ligo-skymap-contour-moc = ligo.skymap.tool.ligo_skymap_contour_moc:main
    - ligo-skymap-flatten = ligo.skymap.tool.ligo_skymap_flatten:main
    - ligo-skymap-unflatten = ligo.skymap.tool.ligo_skymap_unflatten:main
    - ligo-skymap-from-samples = ligo.skymap.tool.ligo_skymap_from_samples:main
    - ligo-skymap-constellations = ligo.skymap.tool.ligo_skymap_constellations:main
    - ligo-skymap-plot = ligo.skymap.tool.ligo_skymap_plot:main
    - ligo-skymap-plot-airmass = ligo.skymap.tool.ligo_skymap_plot_airmass:main
    - ligo-skymap-plot-observability = ligo.skymap.tool.ligo_skymap_plot_observability:main
    - ligo-skymap-plot-pp-samples = ligo.skymap.tool.ligo_skymap_plot_pp_samples:main
    - ligo-skymap-plot-stats = ligo.skymap.tool.ligo_skymap_plot_stats:main
    - ligo-skymap-plot-volume = ligo.skymap.tool.ligo_skymap_plot_volume:main
    - ligo-skymap-stats = ligo.skymap.tool.ligo_skymap_stats:main
  error_overdepending: true
  error_overlinking: true
  ignore_run_exports:
    - python
  number: 0
  script:
    - LIGO_SKYMAP_USE_SYSTEM_CHEALPIX=1 {{ PYTHON }} -m pip install . -vv --install-option=--use-system-libraries
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
    - pkg-config
  host:
    - chealpix
    - extension-helpers
    - gsl
    - libcblas
    - libgomp  # [linux and not aarch64]
    - llvm-openmp  # [osx]
    - numpy
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - astroplan >=0.5
    - astropy >=3.1,!=4.0.1
    - astropy-healpix >=0.3
    - chealpix
    - gsl
    - healpy
    - h5py
    - importlib_resources  # [py<37]
    - libcblas
    - ligo-common
    - ligo-gracedb >=2.0.1
    - ligo-segments >=1.2.0
    - llvm-openmp  # [osx]
    - lscsoft-glue >=2.0.0
    - matplotlib >=3.0.2
    - networkx
    - {{ pin_compatible('numpy') }}
    - pillow >=2.5.0
    - ptemcee
    - python
    - python-lal >=6.19.2
    - python-lalinspiral >=1.8.1
    - python-lalmetaio >=1.5.0
    - python-lalsimulation >=1.8.2
    - python-ligo-lw
    - pytz
    - reproject >=0.3.2
    - scipy >=0.14
    - tqdm

test:
  imports:
    - ligo.skymap
    - ligo.skymap.bayestar
    - ligo.skymap.bayestar.ez_emcee
    - ligo.skymap.bayestar.filter
    - ligo.skymap.bayestar.interpolation
    - ligo.skymap.bayestar.ptemcee
    - ligo.skymap.conftest
    - ligo.skymap.coordinates
    - ligo.skymap.coordinates.detector
    - ligo.skymap.coordinates.eigenframe
    - ligo.skymap.distance
    - ligo.skymap.extern
    - ligo.skymap.extern.quantile
    - ligo.skymap.healpix_tree
    - ligo.skymap.io
    - ligo.skymap.io.events
    - ligo.skymap.io.events.base
    - ligo.skymap.io.events.detector_disabled
    - ligo.skymap.io.events.gracedb
    - ligo.skymap.io.events.hdf
    - ligo.skymap.io.events.ligolw
    - ligo.skymap.io.events.magic
    - ligo.skymap.io.events.sqlite
    - ligo.skymap.io.fits
    - ligo.skymap.io.hdf5
    - ligo.skymap.kde
    - ligo.skymap.moc
    - ligo.skymap.plot
    - ligo.skymap.plot.allsky
    - ligo.skymap.plot.angle
    - ligo.skymap.plot.backdrop
    - ligo.skymap.plot.cmap
    - ligo.skymap.plot.cylon
    - ligo.skymap.plot.itrs_frame_monkeypatch
    - ligo.skymap.plot.marker
    - ligo.skymap.plot.poly
    - ligo.skymap.plot.pp
    - ligo.skymap.plot.util
    - ligo.skymap.postprocess
    - ligo.skymap.postprocess.contour
    - ligo.skymap.postprocess.cosmology
    - ligo.skymap.postprocess.crossmatch
    - ligo.skymap.postprocess.ellipse
    - ligo.skymap.postprocess.util
    - ligo.skymap.util
    - ligo.skymap.util.file
    - ligo.skymap.util.numpy
    - ligo.skymap.util.progress
    - ligo.skymap.util.sqlite
    - ligo.skymap.version
  requires:
    - lalapps
    - pytest
  commands:
    - python -m pytest --pyargs "ligo.skymap"
    - bayestar-inject --help
    - bayestar-localize-coincs --help
    - bayestar-localize-lvalert --help
    - bayestar-mcmc --help
    - bayestar-realize-coincs --help
    - bayestar-sample-model-psd --help
    - ligo-skymap-combine --help
    - ligo-skymap-contour --help
    - ligo-skymap-contour-moc --help
    - ligo-skymap-flatten --help
    - ligo-skymap-unflatten --help
    - ligo-skymap-from-samples --help
    - ligo-skymap-constellations --help
    - ligo-skymap-plot --help
    - ligo-skymap-plot-airmass --help
    - ligo-skymap-plot-observability --help
    - ligo-skymap-plot-pp-samples --help
    - ligo-skymap-plot-stats --help
    - ligo-skymap-plot-volume --help
    - ligo-skymap-stats --help

about:
  home: https://lscsoft.docs.ligo.org/ligo.skymap/
  doc_url: https://lscsoft.docs.ligo.org/ligo.skymap/
  dev_url: https://git.ligo.org/lscsoft/ligo.skymap
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.rst
  summary: Tools for reading, writing, manipulating, and making LIGO and Virgo sky maps
  description: |
    The `ligo.skymap` package provides tools for reading, writing, generating,
    and visualizing gravitational-wave probability maps from LIGO and Virgo.
    It provides several tools that used to live in LALSuite and elsewhere,
    but in the form of a tiny Python package that is easier to install.

extra:
  recipe-maintainers:
    - duncanmmacleod
