{% set name = "ligo.skymap" %}
{% set version = "2.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('.', '_') }}-{{ version }}.tar.gz
  sha256: 1792bd0f96a36aa8db68996f00601a7e4cd779ce011cdc8ccc7f6d7d2fc9ead3
  patches:
    # remove lalsuite requirement, since we can list dependencies explicitly here
    - pyproject.toml-no-lalsuite.patch
    # don't use extension_helpers to detect openmp
    # see https://git.ligo.org/lscsoft/ligo.skymap/-/issues/32
    - openmp-flags.patch
    # Use posix_memalign instead of aligned_alloc on macOS because aligned_alloc
    # requires macOS >= 10.15 and Conda currently supports macOS >= 10.13
    - posix_memalign.patch  # [osx]

build:
  entry_points:
    - bayestar-inject = ligo.skymap.tool.bayestar_inject:main
    - bayestar-localize-coincs = ligo.skymap.tool.bayestar_localize_coincs:main
    - bayestar-localize-lvalert = ligo.skymap.tool.bayestar_localize_lvalert:main
    - bayestar-mcmc = ligo.skymap.tool.bayestar_mcmc:main
    - bayestar-realize-coincs = ligo.skymap.tool.bayestar_realize_coincs:main
    - bayestar-sample-model-psd = ligo.skymap.tool.bayestar_sample_model_psd:main
    - ligo-skymap-combine = ligo.skymap.tool.ligo_skymap_combine:main
    - ligo-skymap-contour = ligo.skymap.tool.ligo_skymap_contour:main
    - ligo-skymap-contour-moc = ligo.skymap.tool.ligo_skymap_contour_moc:main
    - ligo-skymap-flatten = ligo.skymap.tool.ligo_skymap_flatten:main
    - ligo-skymap-unflatten = ligo.skymap.tool.ligo_skymap_unflatten:main
    - ligo-skymap-from-samples = ligo.skymap.tool.ligo_skymap_from_samples:main
    - ligo-skymap-constellations = ligo.skymap.tool.ligo_skymap_constellations:main
    - ligo-skymap-plot = ligo.skymap.tool.ligo_skymap_plot:main
    - ligo-skymap-plot-airmass = ligo.skymap.tool.ligo_skymap_plot_airmass:main
    - ligo-skymap-plot-coherence = ligo.skymap.tool.ligo_skymap_plot_coherence:main
    - ligo-skymap-plot-observability = ligo.skymap.tool.ligo_skymap_plot_observability:main
    - ligo-skymap-plot-pp-samples = ligo.skymap.tool.ligo_skymap_plot_pp_samples:main
    - ligo-skymap-plot-stats = ligo.skymap.tool.ligo_skymap_plot_stats:main
    - ligo-skymap-plot-volume = ligo.skymap.tool.ligo_skymap_plot_volume:main
    - ligo-skymap-stats = ligo.skymap.tool.ligo_skymap_stats:main
  error_overlinking: true
  missing_dso_whitelist:
    # https://github.com/conda/conda-build/issues/5403
    - $RPATH/ld64.so.2  # [ppc64le]
  number: 0
  script:
    - CFLAGS="${CFLAGS} -O3 -flto" CPPFLAGS="${CPPFLAGS} -O3" LIGO_SKYMAP_USE_SYSTEM_CHEALPIX=1 {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<311]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - pkg-config
    # cross-compiling:
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy >=2.0.0                       # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - chealpix
    - extension-helpers
    - gsl
    - libcblas
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - numpy >=2.0.0
    - pip
    - python
    - setuptools >=77
    - setuptools-scm >=8
  run:
    - astroplan >=0.7
    - astropy-base >=6.0
    - astropy-healpix >=0.3
    - chealpix
    - gsl
    - healpy
    - h5py
    - igwn-ligolw
    - igwn-segments
    - libcblas
    - ligo-gracedb >=2.0.1
    - llvm-openmp  # [osx]
    - matplotlib-base >=3.9.1
    - networkx
    - numpy >=2.0.0
    - pillow >=2.5.0
    - ptemcee
    - python
    - python-lal >=7.7.0
    - python-lalinspiral >=5.0.3
    - python-lalmetaio >=4.0.6
    - python-lalsimulation >=6.2.0
    - pytz
    - reproject >=0.3.2
    - scipy >=1.10.1
    - shapely >=2.0.0
    - tqdm >=4.27.0

test:
  requires:
    - lalapps
    - pip
    - pytest
    - pytest-astropy
    - pytest-benchmark
    - pytest-mpl
    - pytest-rerunfailures
  commands:
    # check dependencies
    - python -m pip check
    # run unit tests
    - export OMP_NUM_THREADS={{ CPU_COUNT }}  # [unix]
    - set OMP_NUM_THREADS="{{ CPU_COUNT }}"  # [win]
    - python -m pytest -ra --pyargs "ligo.skymap" --omp-get-num-threads  # [build_platform == target_platform]
    # sanity check entry points
    - bayestar-inject --help
    - bayestar-localize-coincs --help
    - bayestar-localize-lvalert --help
    - bayestar-mcmc --help
    - bayestar-realize-coincs --help
    - bayestar-sample-model-psd --help
    - ligo-skymap-combine --help
    - ligo-skymap-contour --help
    - ligo-skymap-contour-moc --help
    - ligo-skymap-flatten --help
    - ligo-skymap-unflatten --help
    - ligo-skymap-from-samples --help
    - ligo-skymap-constellations --help
    - ligo-skymap-plot --help
    - ligo-skymap-plot-airmass --help
    - ligo-skymap-plot-observability --help
    - ligo-skymap-plot-pp-samples --help
    - ligo-skymap-plot-stats --help
    - ligo-skymap-plot-volume --help
    - ligo-skymap-stats --help

about:
  home: https://lscsoft.docs.ligo.org/ligo.skymap/
  doc_url: https://lscsoft.docs.ligo.org/ligo.skymap/
  dev_url: https://git.ligo.org/lscsoft/ligo.skymap
  license: GPL-3.0-or-later
  license_file:
    - licenses/LICENSE.rst
    - licenses/CHEALPIX_LICENSE.rst
    - licenses/NUMPY_LICENSE.rst
    - licenses/TEMPLATE_LICENCE.rst
  license_family: GPL
  summary: Tools for reading, writing, manipulating, and making LIGO and Virgo sky maps
  description: |
    The `ligo.skymap` package provides tools for reading, writing, generating,
    and visualizing gravitational-wave probability maps from LIGO and Virgo.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - lpsinger
