{% set name = "ligo.skymap" %}
{% set version = "0.4.0" %}
{% set sha256 = "f381b8d8cf7c5a221b7d7288155917d5bbfd31e878de69d3e83c7ead00d9fc52" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # remove lalsuite requirement, since we can list dependencies explicitly here
    - setup.cfg-no-lalsuite.patch

build:
  entry_points:
    - bayestar-inject = ligo.skymap.tool.bayestar_inject:main
    - bayestar-localize-coincs = ligo.skymap.tool.bayestar_localize_coincs:main
    - bayestar-localize-lvalert = ligo.skymap.tool.bayestar_localize_lvalert:main
    - bayestar-mcmc = ligo.skymap.tool.bayestar_mcmc:main
    - bayestar-realize-coincs = ligo.skymap.tool.bayestar_realize_coincs:main
    - bayestar-sample-model-psd = ligo.skymap.tool.bayestar_sample_model_psd:main
    - ligo-skymap-combine = ligo.skymap.tool.ligo_skymap_combine:main
    - ligo-skymap-contour = ligo.skymap.tool.ligo_skymap_contour:main
    - ligo-skymap-contour-moc = ligo.skymap.tool.ligo_skymap_contour_moc:main
    - ligo-skymap-flatten = ligo.skymap.tool.ligo_skymap_flatten:main
    - ligo-skymap-unflatten = ligo.skymap.tool.ligo_skymap_unflatten:main
    - ligo-skymap-from-samples = ligo.skymap.tool.ligo_skymap_from_samples:main
    - ligo-skymap-constellations = ligo.skymap.tool.ligo_skymap_constellations:main
    - ligo-skymap-plot = ligo.skymap.tool.ligo_skymap_plot:main
    - ligo-skymap-plot-airmass = ligo.skymap.tool.ligo_skymap_plot_airmass:main
    - ligo-skymap-plot-observability = ligo.skymap.tool.ligo_skymap_plot_observability:main
    - ligo-skymap-plot-pp-samples = ligo.skymap.tool.ligo_skymap_plot_pp_samples:main
    - ligo-skymap-plot-stats = ligo.skymap.tool.ligo_skymap_plot_stats:main
    - ligo-skymap-plot-volume = ligo.skymap.tool.ligo_skymap_plot_volume:main
    - ligo-skymap-stats = ligo.skymap.tool.ligo_skymap_stats:main
  error_overdepending: true
  error_overlinking: true
  ignore_run_exports:
    - python
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - clangdev
    - pkg-config
  host:
    - chealpix
    - extension-helpers
    - gsl
    - libcblas
    - intel-openmp
    - icc_rt
    - llvm-openmp
    - numpy
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - astroplan >=0.5
    - astropy >=3.1,!=4.0.1
    - astropy-healpix >=0.3
    - chealpix
    - gsl
    - healpy
    - h5py
    - importlib_resources  # [py<37]
    - libcblas
    - ligo-common
    - ligo-gracedb >=2.0.1
    - ligo-segments >=1.2.0
    - intel-openmp
    - icc_rt
    - matplotlib >=3.0.2
    - networkx
    - {{ pin_compatible('numpy') }}
    - pillow >=2.5.0
    - ptemcee
    - python
    - python-lal >=6.19.2
    - python-lalinspiral >=1.8.1
    - python-lalmetaio >=1.5.0
    - python-lalsimulation >=1.8.2
    - python-ligo-lw
    - pytz
    - reproject >=0.3.2
    - scipy >=0.14
    - tqdm >=4.27.0

about:
  home: https://lscsoft.docs.ligo.org/ligo.skymap/
  doc_url: https://lscsoft.docs.ligo.org/ligo.skymap/
  dev_url: https://git.ligo.org/lscsoft/ligo.skymap
  license: GPL-3.0-or-later
  license_file:
    - licenses/LICENSE.rst
    - licenses/CHEALPIX_LICENSE.rst
    - licenses/NUMPY_LICENSE.rst
    - licenses/TEMPLATE_LICENCE.rst
  license_family: GPL
  summary: Tools for reading, writing, manipulating, and making LIGO and Virgo sky maps
  description: |
    The `ligo.skymap` package provides tools for reading, writing, generating,
    and visualizing gravitational-wave probability maps from LIGO and Virgo.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - lpsinger
